"""
Django settings for JmanOps project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import posixpath

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_NAME = 'JourneyMan Pictures Ltd'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '80628eb4-c768-48ee-8e85-838a723a57e3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#https://jmanops.azurewebsites.net
ALLOWED_HOSTS = ['jmanops.azurewebsites.net','localhost']



# Application definition

INSTALLED_APPS = [
    'app',
    # Add your apps here to enable them
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django.contrib.humanize',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'JmanOps.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JmanOps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
     #'default': {
     #    'ENGINE': 'sql_server.pyodbc',
     #    'NAME': 'JmanOperations',
     #    #'ATOMIC_REQUESTS': 'True',
     #    'HOST': 'DESKTOP-QO5MR5N',
     #    'PORT': 1433,
     #    'USER': 'sa',
     #    'PASSWORD': 'tsb',
     #    'OPTIONS': {
     #       'driver': 'ODBC Driver 13 for SQL Server',
     #   },
     #}
     #,
     'default': {
         'ENGINE': 'sql_server.pyodbc',
         'NAME': 'JmanOperations',
         #'ATOMIC_REQUESTS': 'True',
         'HOST': 'r21sql.database.windows.net',
         'PORT': '',
         'USER': 'sadmin@r21sql.database.windows.net',
         'PASSWORD': 'R1gg1n56!',
         'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
     }

 }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True


DATE_INPUT_FORMATS = [
    '%d %b %Y',            # '25 Oct 2006', '25 Oct, 2006'
    '%d %B %Y',            # '25 October 2006', '25 October, 2006'
]



DATETIME_INPUT_FORMATS = [
    '%d %b %Y %H:%M:%S',            # '25 Oct 2006''
    '%d %B %Y %H:%M:%S',            # '25 October 2006'

]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))

CRISPY_TEMPLATE_PACK='bootstrap3'