# Generated by Django 2.0.4 on 2018-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soheader',
            name='SOGUID',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
