# Generated by Django 2.0.4 on 2018-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_soheader_soguid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soheader',
            name='SOGUID',
        ),
    ]
