# Generated by Django 2.0.4 on 2018-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_soheader_soguid'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroSOInvLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('SOID', models.PositiveIntegerField()),
                ('SONumber', models.PositiveIntegerField()),
                ('Code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('RowUpdated', models.DateTimeField(auto_now=True)),
                ('RowInserted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
