# Generated by Django 2.0.4 on 2018-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180607_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('DueDate', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('LineAmountTypes', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('SubTotal', models.FloatField(default=0)),
                ('TotalTax', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('UpdatedDateUTC', models.DateTimeField(auto_now=True)),
                ('CurrencyCode', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('Type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('InvoiceID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('AmountDue', models.FloatField(default=0)),
                ('AmountPaid', models.FloatField(default=0)),
                ('AmountCredited', models.FloatField(default=0)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
                ('HasAttachments', models.BooleanField(default=False)),
            ],
        ),
    ]
