# Generated by Django 2.0.4 on 2018-06-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_xerocreditnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xerocreditnotes',
            name='ContactNumber',
        ),
    ]
