# Generated by Django 2.0.4 on 2018-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_xerocreditnotes_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllCreditNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ContactID', models.CharField(blank=True, default='', max_length=64)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('LineAmountTypes', models.CharField(max_length=20, null=True)),
                ('SubTotal', models.FloatField(default=0, null=True)),
                ('TotalTax', models.FloatField(default=0, null=True)),
                ('CISDeduction', models.FloatField(default=0, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
                ('CurrencyCode', models.CharField(blank=True, max_length=4, null=True)),
                ('FullyPaidOnDate', models.DateTimeField(null=True)),
                ('CreditNoteID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('CreditNoteNumber', models.CharField(default='', max_length=50)),
                ('Reference', models.CharField(default='', max_length=50)),
                ('SentToContact', models.BooleanField(default=False)),
                ('RemainingCredit', models.FloatField(default=0, null=True)),
                ('BrandingThemeID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('HasAttachments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XeroAllInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ContactID', models.CharField(blank=True, default='', max_length=64)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('DueDate', models.DateTimeField(null=True)),
                ('Status', models.CharField(max_length=20, null=True)),
                ('LineAmountTypes', models.CharField(max_length=20, null=True)),
                ('SubTotal', models.FloatField(default=0, null=True)),
                ('TotalTax', models.FloatField(default=0, null=True)),
                ('Total', models.FloatField(default=0, null=True)),
                ('TotalDiscount', models.FloatField(default=0, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
                ('CurrencyCode', models.CharField(blank=True, max_length=4, null=True)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
                ('InvoiceID', models.CharField(default='', max_length=64)),
                ('InvoiceNumber', models.CharField(default='', max_length=50)),
                ('Reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('BrandingThemeID', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('Url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('SentToContact', models.BooleanField(default=False)),
                ('ExpectedPaymentDate', models.DateTimeField(null=True)),
                ('PlannedPaymentDate', models.DateTimeField(null=True)),
                ('HasAttachments', models.BooleanField(default=False)),
                ('AmountDue', models.FloatField(default=0, null=True)),
                ('AmountPaid', models.FloatField(default=0, null=True)),
                ('CISDeduction', models.FloatField(default=0, null=True)),
                ('FullyPaidOnDate', models.DateTimeField(null=True)),
                ('AmountCredited', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XeroAllPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentID', models.CharField(blank=True, default='', max_length=64)),
                ('AccountID', models.CharField(blank=True, default='', max_length=64)),
                ('Date', models.DateTimeField(null=True)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
                ('BankAmount', models.FloatField(default=0, null=True)),
                ('Amount', models.FloatField(default=0, null=True)),
                ('Reference', models.CharField(default='', max_length=50)),
                ('IsReconciled', models.BooleanField(default=False)),
                ('Status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('PaymentType', models.CharField(blank=True, max_length=20, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
                ('Code', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
