# Generated by Django 2.0.4 on 2018-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_xeroallcreditnotes_xeroallinvoices_xeroallpayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllOverPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID', models.CharField(blank=True, default='', max_length=64)),
                ('Name', models.CharField(blank=True, default='', max_length=64)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('LineAmountTypes', models.CharField(max_length=20, null=True)),
                ('SubTotal', models.FloatField(default=0, null=True)),
                ('TotalTax', models.FloatField(default=0, null=True)),
                ('Total', models.FloatField(default=0, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
                ('CurrencyCode', models.CharField(blank=True, max_length=4, null=True)),
                ('Type', models.DateTimeField(null=True)),
                ('RemainingCredit', models.FloatField(default=0, null=True)),
                ('HasAttachments', models.BooleanField(default=False)),
                ('OverpaymentID', models.CharField(blank=True, default='', max_length=64)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XeroAllPrePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID', models.CharField(blank=True, default='', max_length=64)),
                ('Name', models.CharField(blank=True, default='', max_length=64)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('LineAmountTypes', models.CharField(max_length=20, null=True)),
                ('SubTotal', models.FloatField(default=0, null=True)),
                ('TotalTax', models.FloatField(default=0, null=True)),
                ('Total', models.FloatField(default=0, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
                ('CurrencyCode', models.CharField(blank=True, max_length=4, null=True)),
                ('Type', models.DateTimeField(null=True)),
                ('RemainingCredit', models.FloatField(default=0, null=True)),
                ('HasAttachments', models.BooleanField(default=False)),
                ('PrepaymentID', models.CharField(blank=True, default='', max_length=64)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
                ('Reference', models.CharField(max_length=20, null=True)),
                ('FullyPaidOnDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
