# Generated by Django 2.0.4 on 2018-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180608_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='XeroContactID',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='XeroUpdateFail',
            field=models.BooleanField(default=False),
        ),
    ]
