# Generated by Django 2.0.4 on 2018-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180611_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Code',
            field=models.CharField(db_index=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='XeroUpdateFail',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
