# Generated by Django 2.0.4 on 2018-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180611_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroTranView',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('TRANTYPE', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('SubTotal', models.FloatField(default=0, null=True)),
                ('TotalTax', models.FloatField(default=0, null=True)),
                ('Total', models.FloatField(default=0, null=True)),
                ('CurrencyCode', models.CharField(max_length=4, null=True)),
                ('CurrencyRate', models.FloatField(default=1, null=True)),
                ('InvoiceNumber', models.CharField(max_length=20, null=True)),
                ('Reference', models.CharField(max_length=20, null=True)),
                ('AmountDue', models.FloatField(default=0, null=True)),
                ('AmountPaid', models.FloatField(default=0, null=True)),
                ('UpdatedDateUTC', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'r21_vw_XeroTransactions',
                'managed': False,
            },
        ),
    ]
