# Generated by Django 2.0.4 on 2018-06-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_xerotranview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
