# Generated by Django 2.0.4 on 2018-06-11 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180611_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroalloverpayments',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xeroalloverpayments',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
