# Generated by Django 2.0.4 on 2018-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_xeroallinvoices2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XeroAllInvoices2',
        ),
    ]
