# Generated by Django 2.0.4 on 2018-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_xeroallcreditnotes_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroallcreditnotes',
            name='Total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
