# Generated by Django 2.0.4 on 2018-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20180626_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactID', models.CharField(blank=True, default='', max_length=64)),
                ('AddressType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('AddressLine1', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('AddressLine2', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('AddressLine3', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('AddressLine4', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('City', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Region', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PostalCode', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('Country', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('AttentionTo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
