# Generated by Django 2.0.4 on 2018-06-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_xeroalladdresses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xeroalladdresses',
            unique_together={('ContactID', 'AddressType')},
        ),
    ]
