# Generated by Django 2.0.4 on 2018-06-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180626_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AddressLine1',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AddressLine2',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AddressLine3',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AddressLine4',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AddressType',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='AttentionTo',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='City',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='xeroallcontacts',
            name='Region',
        ),
    ]
