# Generated by Django 2.0.4 on 2018-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_xeroallcontactpersons'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllTaxRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('TaxType', models.CharField(blank=True, default='', max_length=20)),
                ('CanApplyToAssets', models.BooleanField(default=False)),
                ('CanApplyToEquity', models.BooleanField(default=False)),
                ('CanApplyToExpenses', models.BooleanField(default=False)),
                ('CanApplyToLiabilities', models.BooleanField(default=False)),
                ('CanApplyToRevenue', models.BooleanField(default=False)),
                ('DisplayTaxRate', models.FloatField(default=0, null=True)),
                ('EffectiveRate', models.FloatField(default=0, null=True)),
                ('Status', models.CharField(blank=True, default='', max_length=20)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
