# Generated by Django 2.0.4 on 2018-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20180627_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroallaccounts',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
