# Generated by Django 2.0.4 on 2018-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20180627_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, default='', max_length=4, unique=True)),
                ('Description', models.CharField(blank=True, default='', max_length=240)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
