# Generated by Django 2.0.4 on 2018-06-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180627_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xeroallitems',
            old_name='UnitPrice',
            new_name='CostUnitPrice',
        ),
    ]
