# Generated by Django 2.0.4 on 2018-06-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20180627_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllCreditNoteAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditNoteID', models.CharField(blank=True, default='', max_length=64)),
                ('CreditNoteNumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ContactName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('InvoiceID', models.CharField(blank=True, default='', max_length=64)),
                ('InvoiceNumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Amount', models.FloatField(default=0, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
