# Generated by Django 2.0.4 on 2018-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_xeroallcreditnoteallocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAllJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JournalID', models.CharField(blank=True, default='', max_length=64)),
                ('JournalDate', models.DateTimeField(null=True)),
                ('JournalNumber', models.CharField(blank=True, default='', max_length=50)),
                ('CreatedDateUTC', models.DateTimeField(null=True)),
                ('Reference', models.CharField(blank=True, default='', max_length=50)),
                ('SourceID', models.CharField(blank=True, default='', max_length=64)),
                ('SourceType', models.CharField(blank=True, default='', max_length=20)),
                ('JournalLineID', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('AccountID', models.CharField(blank=True, default='', max_length=64)),
                ('AccountCode', models.CharField(blank=True, default='', max_length=50)),
                ('AccountType', models.CharField(blank=True, default='', max_length=20)),
                ('AccountName', models.CharField(blank=True, default='', max_length=100)),
                ('Description', models.CharField(blank=True, default='', max_length=1000)),
                ('NetAmount', models.FloatField(default=0, null=True)),
                ('GrossAmount', models.FloatField(default=0, null=True)),
                ('TaxAmount', models.FloatField(default=0, null=True)),
                ('TaxType', models.CharField(blank=True, default='', max_length=50)),
                ('TaxName', models.CharField(blank=True, default='', max_length=100)),
                ('TrackingCategoryID', models.CharField(blank=True, default='', max_length=64)),
                ('CategoryName', models.CharField(blank=True, default='', max_length=50)),
                ('TrackingOptionID', models.CharField(blank=True, default='', max_length=64)),
                ('OptionName', models.CharField(blank=True, default='', max_length=50)),
                ('Status', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
