# Generated by Django 2.0.4 on 2018-06-28 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_xeroalljournals'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroalljournals',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xeroalljournals',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
